export const ALL_WASHING_MACHINE_REQUEST = "ALL_WASHING_MACHINE_REQUEST";
export const ALL_WASHING_MACHINE_SUCCESS = "ALL_WASHING_MACHINE_SUCCESS";
export const ALL_WASHING_MACHINE_FAIL = "ALL_WASHING_MACHINE_FAIL";

export const WASHING_MACHINE_DETAIL_REQUEST = "WASHING_MACHINE_DETAIL_REQUEST";
export const WASHING_MACHINE_DETAIL_SUCCESS = "WASHING_MACHINE_DETAIL_SUCCESS";
export const WASHING_MACHINE_DETAIL_FAIL = "WASHING_MACHINE_DETAIL_FAIL";

export const UPDATE_WASHING_MACHINE_REQUEST = "UPDATE_WASHING_MACHINE_REQUEST";
export const UPDATE_WASHING_MACHINE_SUCCESS = "UPDATE_WASHING_MACHINE_SUCCESS";
export const UPDATE_WASHING_MACHINE_FAIL = "UPDATE_WASHING_MACHINE_FAIL";
export const UPDATE_WASHING_MACHINE_RESET = "UPDATE_WASHING_MACHINE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
